#!/usr/bin/env python3
"""
Build Structured Wandering's curated destination pages from the travelbrain
curation engine (ADR-085) -> <destination>/index.html.

The brain is the source of truth; this builder is the showcase renderer.

    brain/curation.duckdb            (travelbrain repo — taste, evidence, decisions)
          |  site/scripts/export_content.py     (existing SQL->JSON bridge)
          v
       content.json                  (pages[] + venues[] + pois[] + header_image)
          |  build_curated.py        (THIS FILE — Structured Wandering chrome)
          v
    structuredwandering.com/italy/   (the showcase)

Why not Astro: SW is plain static HTML generated by the sibling Python builders
(build_articles.py / build_books.py). One domain, one build family, one style —
so this imports their helpers rather than re-implementing markdown/chrome.
See ADR-085 "Considered alternatives".

WHAT MAKES THIS A SHOWCASE, NOT A LISTICLE
Ordinary travel pages show picks. This shows *why* — the system is the story:
  - the versioned taste rubric that scored each venue (style_fit),
  - the ANTI-INTERESTS / hard-exclude gate: what we ruled OUT and why,
  - the evidence trail (which curated sources mentioned it),
  - the human approve step,
  - honest links: affiliate ONLY where the brain has a real provider mapping;
    never a fabricated URL (the exporter already guarantees this).

PUBLISH GATE (mirrors the book layer, ADR-068 SS1b): a destination publishes only
with real content + a header image + at least one venue. Anything else is held
back. Draft pages never reach the live site.

Usage:
    python build_curated.py                     # build every ready destination
    python build_curated.py --content path.json # explicit brain export
    python build_curated.py --draft             # include status=draft (preview)
    SW_CONTENT_JSON=... python build_curated.py
"""
from __future__ import annotations

import os
import re
import json
import html
import argparse
import unicodedata
from pathlib import Path

# Reuse the SW article builder's helpers so the builders never drift.
from build_articles import split_frontmatter, md_to_html, BASE_URL  # noqa: F401

HERE = Path(__file__).parent
# The brain's export. Cross-repo artifact (ADR-085 phase 3 decides how it travels);
# default looks for a local copy committed/dropped next to this builder.
CONTENT_JSON = Path(os.environ.get("SW_CONTENT_JSON", str(HERE / "curated" / "content.json")))

# Only these statuses publish. 'draft' requires --draft (preview only).
PUBLISH_STATUS = {"ready", "published"}


def esc(s) -> str:
    return html.escape(str(s or ""), quote=True)


def slugify(s: str) -> str:
    """ASCII, url-safe. NB: Python's \\w matches unicode letters, so 'Cefalù' would
    keep the 'ù' and yield a non-ASCII path — fold to ASCII first."""
    s = unicodedata.normalize("NFKD", str(s or "")).encode("ascii", "ignore").decode()
    s = re.sub(r"[^\w\s-]", "", s).strip().lower()
    return re.sub(r"[-\s]+", "-", s)


# --------------------------------------------------------------------------
# Publish gate
# --------------------------------------------------------------------------

def is_complete(page: dict) -> tuple[bool, str]:
    """A destination goes live only when it actually stands up. Returns (ok, why)."""
    if not (page.get("body_md") or "").strip():
        return False, "no body"
    if not page.get("venues"):
        return False, "no venues"
    if not page.get("header_image"):
        return False, "no header image"
    return True, ""


# --------------------------------------------------------------------------
# Renderers — the parts that make the system visible
# --------------------------------------------------------------------------

def render_link(link: dict | None) -> str:
    """Honest links. affiliate -> rel=sponsored; own site -> rel=nofollow; else say so."""
    if not link:
        return '<span class="no-link">No booking link — we haven\'t vetted one.</span>'
    kind = link.get("kind")
    rel = "sponsored nofollow noopener" if kind == "affiliate" else "nofollow noopener"
    cls = "venue-link venue-link--affiliate" if kind == "affiliate" else "venue-link"
    label = esc(link.get("label") or "Visit")
    out = (f'<a class="{cls}" href="{esc(link.get("url"))}" rel="{rel}" '
           f'target="_blank">{label}</a>')
    if kind == "affiliate":
        out += ('<span class="aff-note">affiliate link — we may earn a commission, '
                'at no cost to you</span>')
    return out


def render_evidence(sources: list) -> str:
    """The provenance trail: which curated sources put this on our radar."""
    if not sources:
        return ""
    items = " · ".join(esc(s) for s in sources)
    return (f'<p class="evidence"><span class="evidence-label">Evidence</span> {items}</p>')


def render_venue(v: dict) -> str:
    # style_fit arrives as a STRING from the export (DuckDB DECIMAL -> JSON string),
    # so don't isinstance-check for a number — coerce, and drop only if truly absent.
    fit_html = ""
    try:
        if v.get("style_fit") not in (None, ""):
            fit_html = (f'<span class="taste-score" title="taste-rubric score">'
                        f'{round(float(v["style_fit"]))}</span>')
    except (TypeError, ValueError):
        fit_html = ""
    flags = []
    if v.get("adults_only"):
        flags.append('<span class="flag">adults only</span>')
    if v.get("ownership"):
        flags.append(f'<span class="flag">{esc(v["ownership"])}</span>')
    if v.get("venue_type"):
        flags.append(f'<span class="flag">{esc(v["venue_type"])}</span>')
    img = ""
    if v.get("image"):
        im = v["image"]
        credit = ""
        if im.get("photographer"):
            credit = (f'<figcaption>Photo: <a href="{esc(im.get("photographer_url"))}" '
                      f'rel="nofollow noopener">{esc(im["photographer"])}</a>'
                      f'{" · " + esc(im.get("provider")) if im.get("provider") else ""}</figcaption>')
        img = (f'<figure class="venue-img"><img loading="lazy" src="{esc(im.get("url_full"))}" '
               f'alt="{esc(im.get("alt_text") or v.get("name"))}">{credit}</figure>')
    return (
        f'<article class="venue">\n'
        f'  {img}\n'
        f'  <div class="venue-body">\n'
        f'    <h3>{esc(v.get("name"))} {fit_html}</h3>\n'
        f'    <p class="flags">{"".join(flags)}</p>\n'
        f'    {f"<p class=\"notes\">{esc(v.get('design_notes'))}</p>" if v.get("design_notes") else ""}\n'
        f'    {render_evidence(v.get("sources") or [])}\n'
        f'    <p class="link-row">{render_link(v.get("link"))}</p>\n'
        f'  </div>\n'
        f'</article>'
    )


def render_pois(pois: list) -> str:
    """Places we actually stood in — our own photos, not stock."""
    if not pois:
        return ""
    cards = []
    for p in pois:
        img = (f'<img loading="lazy" src="{esc(p.get("rep_photo"))}" alt="{esc(p.get("name"))}">'
               if p.get("rep_photo") else "")
        cards.append(
            f'<figure class="poi">{img}<figcaption><strong>{esc(p.get("name"))}</strong>'
            f'{f" — {esc(p.get('blurb'))}" if p.get("blurb") else ""}</figcaption></figure>'
        )
    return ('<section class="pois">\n'
            '  <h2>We stood here</h2>\n'
            '  <p class="section-note">Our own photographs — not stock, not a feed.</p>\n'
            f'  <div class="poi-grid">{"".join(cards)}</div>\n'
            '</section>')


def render_method(page: dict) -> str:
    """The differentiator: show the system, including what it ruled OUT."""
    fm = page.get("frontmatter") or {}
    taste = fm.get("taste_profile") or "adults · design-led · quiet"
    excluded = fm.get("excluded") or ["family-oriented", "chain", "party"]
    ex = "".join(f'<li>{esc(x)}</li>' for x in excluded)
    return (
        '<section class="method">\n'
        '  <h2>How this list was chosen</h2>\n'
        f'  <p>Every venue here was scored against an explicit, versioned taste profile — '
        f'<strong>{esc(taste)}</strong> — not a popularity feed. The score you see next to each '
        f'name is that rubric\'s output.</p>\n'
        '  <div class="method-cols">\n'
        '    <div class="method-col">\n'
        '      <h3>What we ruled out</h3>\n'
        '      <p class="section-note">Our anti-interests are part of the model. A hard gate '
        'excludes these before anything is scored:</p>\n'
        f'      <ul class="excluded">{ex}</ul>\n'
        '    </div>\n'
        '    <div class="method-col">\n'
        '      <h3>Where it comes from</h3>\n'
        '      <p class="section-note">Each pick carries its evidence: the curated sources that '
        'mentioned it. Corroboration across independent sources raises the score — a single '
        'press release does not.</p>\n'
        '    </div>\n'
        '    <div class="method-col">\n'
        '      <h3>A human approves</h3>\n'
        '      <p class="section-note">The system shortlists; we approve. Nothing publishes '
        'because a machine liked it.</p>\n'
        '    </div>\n'
        '  </div>\n'
        '</section>'
    )


PAGE = """<!doctype html>
<html lang="en">
<head>
<meta charset="utf-8"/>
<meta name="viewport" content="width=device-width, initial-scale=1"/>
<title>{title} — Structured Wandering</title>
<meta name="description" content="{subtitle}"/>
<meta name="author" content="Jaco van der Laan &amp; Annemarie van der Laan"/>
<link rel="canonical" href="{canonical}"/>
<meta property="og:title" content="{title}"/>
<meta property="og:description" content="{subtitle}"/>
<meta property="og:type" content="article"/>
<meta property="og:url" content="{canonical}"/>
<meta property="og:site_name" content="Structured Wandering"/>
<meta property="og:image" content="{og_image}"/>
<meta name="twitter:card" content="summary_large_image"/>
<link rel="icon" type="image/svg+xml" href="../assets/favicon.svg"/>
<link rel="stylesheet" href="../assets/site.css"/>
<link rel="stylesheet" href="../assets/curated.css"/>
<script type="application/ld+json">
{json_ld}
</script>
</head>
<body>
<header class="site"><div class="wrap">
  <a class="brand" href="../">Structured&nbsp;<span>Wandering</span></a>
  <a class="back" href="../#curation">← What's curated</a>
</div></header>
<main class="wrap curated">
  <p class="eyebrow">Curated · {destination}</p>
  <h1>{title}</h1>
  <p class="subtitle">{subtitle}</p>
  {header_image}
  <div class="intro">
{body}
  </div>
{method}
  <section class="venues">
    <h2>The shortlist</h2>
{venues}
  </section>
{pois}
  <div class="curated-cta">
    <p class="formula-mini">Structure + Taste + Sources → Journeys worth taking</p>
    <a class="btn btn-ghost" href="https://structurebeatsmagic.com">The method behind it →</a>
  </div>
</main>
<footer><div class="wrap">Structured Wandering — deliberate travel, curated by
  Jaco &amp; Annemarie</div></footer>
</body></html>
"""


def build_jsonld(title, subtitle, canonical, image, destination):
    data = {
        "@context": "https://schema.org", "@type": "Article",
        "headline": title, "description": subtitle, "url": canonical,
        "about": {"@type": "Place", "name": destination},
        "author": [{"@type": "Person", "name": "Jaco van der Laan"},
                   {"@type": "Person", "name": "Annemarie van der Laan"}],
        "publisher": {"@type": "Organization", "name": "Structured Wandering",
                      "url": BASE_URL},
    }
    if image:
        data["image"] = image
    return json.dumps(data, indent=2, ensure_ascii=False)


def render_header_image(hdr: dict | None) -> str:
    if not hdr:
        return ""
    credit = ""
    if hdr.get("photographer"):
        credit = (f'<figcaption>Photo: <a href="{esc(hdr.get("photographer_url"))}" '
                  f'rel="nofollow noopener">{esc(hdr["photographer"])}</a>'
                  f'{" · " + esc(hdr.get("provider")) if hdr.get("provider") else ""}</figcaption>')
    return (f'<figure class="hero-figure"><img src="{esc(hdr.get("url_full"))}" '
            f'alt="{esc(hdr.get("alt_text"))}">{credit}</figure>')


def main() -> None:
    ap = argparse.ArgumentParser()
    ap.add_argument("--content", default=str(CONTENT_JSON),
                    help="brain export JSON (default: curated/content.json)")
    ap.add_argument("--draft", action="store_true",
                    help="also build status=draft pages (preview; not for publish)")
    args = ap.parse_args()

    src = Path(args.content)
    if not src.is_file():
        raise SystemExit(
            f"brain export not found: {src}\n"
            f"  Produce it in the travelbrain repo:\n"
            f"    python site/scripts/export_content.py   # -> site/src/content.json\n"
            f"  then copy it to {CONTENT_JSON} (ADR-085 phase 3 formalises this bridge).")

    data = json.loads(src.read_text(encoding="utf-8"))
    pages = data.get("pages") if isinstance(data, dict) else data
    if not pages:
        raise SystemExit("brain export has no pages")

    allowed = set(PUBLISH_STATUS) | ({"draft"} if args.draft else set())
    built = held = 0
    for pg in pages:
        status = (pg.get("status") or "").lower()
        if status not in allowed:
            continue
        fm = pg.get("frontmatter") or {}
        destination = fm.get("destination") or pg.get("title") or "Somewhere"
        slug = slugify(fm.get("path") or destination)

        ok, why = is_complete(pg)
        if not ok and not args.draft:
            print(f"  held back: {slug} ({why})")
            held += 1
            continue

        title = pg.get("title") or destination
        subtitle = fm.get("subtitle") or f"Chosen, not found — {destination} for adults."
        canonical = f"{BASE_URL}/{slug}/"
        hdr = pg.get("header_image") or {}
        og = hdr.get("url_full") or ""
        venues_html = "\n".join(render_venue(v) for v in (pg.get("venues") or []))

        out_dir = HERE / slug
        out_dir.mkdir(parents=True, exist_ok=True)
        (out_dir / "index.html").write_text(PAGE.format(
            title=esc(title), subtitle=esc(subtitle), destination=esc(destination),
            canonical=canonical, og_image=esc(og),
            json_ld=build_jsonld(title, subtitle, canonical, og, destination),
            header_image=render_header_image(pg.get("header_image")),
            body=md_to_html(pg.get("body_md") or ""),
            method=render_method(pg),
            venues=venues_html,
            pois=render_pois(pg.get("pois") or []),
        ), encoding="utf-8")
        n_v = len(pg.get("venues") or [])
        aff = sum(1 for v in pg.get("venues") or []
                  if (v.get("link") or {}).get("kind") == "affiliate")
        print(f"  + {slug}/index.html  ({n_v} venues, {aff} affiliate link(s), status={status})")
        built += 1

    print(f"built {built} destination(s)" + (f", held back {held}" if held else ""))


if __name__ == "__main__":
    main()
